### ISSUE TITLE
ENOENT issue with Polyfill

### ISSUE THREAD

**Issue by emathiasen** [pixelcabin/ziplines#1]
Getting the following error when running: `$ ziplines new`

Its related to the graceful-fs module.
#### Error:

```
/usr/local/lib/node_modules/ziplines/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:15
  chdir.call(process, d)
        ^
Error: ENOENT, no such file or directory
    at Error (native)
    at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/update-notifier/node_modules/configstore/node_modules/graceful-fs/polyfills.js:15:9)
    at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/bower/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/npm/node_modules/graceful-fs/polyfills.js:14:9)
    at /usr/local/lib/node_modules/ziplines/lib/commands/new.js:145:17
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ziplines/node_modules/exec/exec.js:90:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)`
```

Running latest version of ziplines

**Comment by michaelrshannon** [comment]
Hi @emathiasen - thanks for this - will investigate.

**Comment by michaelrshannon** [comment]
4c0e723fc16bf461388c3805745d3b2b1437a35b may have resolved this issue - after updating, if you hit an error, try running the `new` command with `sudo`. Let me know if that works!
