### ISSUE TITLE
`ziplines status` shows error when nothing setup

### ISSUE THREAD

**Issue by reggi** [pixelcabin/ziplines#4]
``` bash
thomasreggi@zx:ziplines$ ziplines status
{ [Error: ENOENT: no such file or directory, open 'credentials.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'credentials.json' }
{ [Error: ENOENT: no such file or directory, open 'Gruntfile.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Gruntfile.js' }
{ [Error: ENOENT: no such file or directory, open 'Gruntfile.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Gruntfile.js' }
/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/ziplines/lib/commands/status.js:25
  var apiKey = credentials.api_key ? credentials.api_key.blue : 'Missing'.red;
                          ^

TypeError: Cannot read property 'api_key' of undefined
    at Object.module.exports [as status] (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/ziplines/lib/commands/status.js:25:27)
    at Object.<anonymous> (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/ziplines/bin/cli.js:52:26)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by michaelrshannon** [comment]
Thanks @reggi - will improve the error handling of this scenario.

**Comment by reggi** [comment]
Another weird `ziplines status` error.

```
[TypeError: Cannot read property 'split' of undefined]
/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/ziplines/lib/commands/status.js:28
  env = env === 'development' ? env.blue : env.green;
                                              ^

TypeError: Cannot read property 'green' of undefined
    at Object.module.exports [as status] (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/ziplines/lib/commands/status.js:28:47)
    at Object.<anonymous> (/Users/thomasreggi/.nvm/versions/node/v5.3.0/lib/node_modules/ziplines/bin/cli.js:52:26)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```
