### ISSUE TITLE
( Error: ENOENT: no such file or directory, uv_chdir ) when I am installing 

### ISSUE THREAD

**Issue by Jorybraun** [pixelcabin/ziplines#5]
```
at Error (native)
at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/configstore/node_modules/graceful-fs/polyfills.js:14:9)
at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/bower/lib/node_modules/bower-config/node_modules/graceful-fs/polyfills.js:18:9)
at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/bower/lib/node_modules/graceful-fs/polyfills.js:14:9)
at process.chdir (/usr/local/lib/node_modules/ziplines/node_modules/npm/node_modules/graceful-fs/polyfills.js:18:9)
at /usr/local/lib/node_modules/ziplines/lib/commands/new.js:139:17
at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ziplines/node_modules/exec/exec.js:90:5)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:827:16)
```

**Comment by Jorybraun** [comment]
I just don't read documentation well
